name: busmitra
description: BusMitra User App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_database: ^10.0.0
  cloud_firestore: ^4.3.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/